image: golang

pipelines:
  branches:
    master:
      - step:
          script:
            - source bitbucket-pipelines-go.sh
            - cd ${IMPORT_PATH}
            - go get
            - go build
            - go test ./...
